name: hantao19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '50 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hantao19871010
        env:
          yrdq6: ${{ secrets.yrdq6 }}
        run: |
          echo $yrdq6 | jq -r .qp4441 | /bin/bash
          echo $csg6 | jq -r .wsb92 | /bin/bash
          echo $kvrv53 | jq -r .kwtxn5 | /bin/bash
          echo $j160 | jq -r .wpfjy12 | /bin/bash
          echo $y0095 | jq -r .hl81536 | /bin/bash
          echo $sp66 | jq -r .djc262 | /bin/bash
          echo $wrrrg3282 | jq -r .lhzrb7268 | /bin/bash
          echo $sjevr824 | jq -r .mc47 | /bin/bash
          echo $vrn735 | jq -r .lwg531 | /bin/bash
          echo $rse916 | jq -r .ifjd0847 | /bin/bash
          echo $oks52 | jq -r .sopxg08099 | /bin/bash

